### ISSUE TITLE
import bedtools?

### ISSUE THREAD

**Issue by laserson** [mlibbrecht/submodular_sequence_repset#1]
`repset.py` tries to import a package called `bedtools`. However, this package doesn't seem to be used (nor does it exist in PyPI).

**Comment by jun3234** [comment]
Have you solved this problem? I met the same issue.

**Comment by jun3234** [comment]
It is ok to change `import bedtools` to `# import beddtools`

**Comment by mlibbrecht** [comment]
Thanks for noticing this; it is fixed.
