### ISSUE TITLE
math domain error while running psiblast

### ISSUE THREAD

**Issue by mankiddyman** [mlibbrecht/submodular_sequence_repset#6]
Hello, this is my first github post so let me know if I am doing anything wrong

I have a large set of proteins fastas with considerable redundancy, (~2500 proteins)

psiblast_result.tab generates successfully but past this point I get the following error.

```
Loading anaconda3/personal
  Loading requirement: fix_unwritable_tmp fix_setxattr
Loading blast+/2.11.1
  Loading requirement: intel-suite/2019.4
2021-08-09 09:19:35,791 INFO:makeblastdb -in eukarya_filtered_80_qc.fa -input_type fasta -out output/db -dbtype prot
Traceback (most recent call last):
  File "repset.py", line 1584, in <module>
    db = run_psiblast(workdir, args.seqs)
  File "repset.py", line 113, in run_psiblast
    log10_e = math.log10(float(evalue))
ValueError: math domain error

```

I am not sure what may be the cause of the error and would appreciate any help in fixing it.
The tab file is too large to upload so I'll add my input fastas as well as the bash script by which I am running the program.[
[math_error.zip](https://github.com/mlibbrecht/submodular_sequence_repset/files/6953044/math_error.zip)

**Comment by mlibbrecht** [comment]
It looks like the e-value being returned by PSIBLAST is invalid -- either 0, NaN, or something else. You can check the PSIBLAST output (output/psiblast_result.tab) to see if it looks like what you expect. Depending on what you find, you can add some way to handle those values to line 113. For example (in the case where e-value = 0): "if evalue < 1e-10: log10_e = -10".
